# Generated by Django 5.2 on 2026-05-02 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("orgSetup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orgSetup.organizationprofile",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="work_shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.workshift",
            ),
        ),
    ]
